---
- name: Install AWX on Alma Linux 9
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name:  install git
      ansible.builtin.shell: dnf install git -y

    - name: kill the firewall
      ansible.builtin.shell: systemctl disable firewalld

    - name: Install kubnetes
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -


    - name: allow all users to run kubectl
      ansible.builtin.shell: chmod +x /usr/local/bin/kubectl

    - name: allow users to run rancher
      ansible.builtin.shell: chmod +r /etc/rancher/k3s/k3s.yaml

    - name: Kustomize Script
      ansible.builtin.shell: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - name: Move Kustomize file
      ansible.builtin.shell: mv kustomize /usr/local/bin

    - name: Create namespace awx
      ansible.builtin.shell: kubectl create namespace awx
    
    - name: Download Kustomize.yaml file
      ansible.builtin.shell:  wget https://raw.githubusercontent.com/aaronevolved/public/main/awx/kustomization.yaml

    - name: Run Kustomization 
      ansible.builtin.shell: kustomize build . | kubectl apply -f - 

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 3

    - name: 
      ansible.builtin.shell:  kubectl get pods --namespace awx

    - name: Download Kustomize.yaml file
      ansible.builtin.shell:  wget https://raw.githubusercontent.com/aaronevolved/public/main/awx/awx-cr.yaml

    - name: Add awx-cr.yaml to kustomization.yaml
      lineinfile:
        path: /home/zgadmin/kustomization.yaml
        insertafter: 'github.com'
        line:  '  - awx-cr.yaml'

    - name: Run Kustomization 2nd time.
      ansible.builtin.shell: kustomize build . | kubectl apply -f - 

    - name: Pause for 15 minutes to build app cache
      ansible.builtin.pause:
        minutes: 15

    - name: List pods
      ansible.builtin.shell:  kubectl get pods --namespace awx

    - name: get password 
      ansible.builtin.shell:  kubectl get secret awx-admin-password -n awx -o jsonpath="{.data.password}" | base64 --decode
      register: awxpassword

    - name: Messages for your sir
      ansible.builtin.debug:
        msg: 
        - "The Default User is admin"
        - "The default password is {{ awxpassword }}"

    - name: Reboot machine and send a message
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
