---
- name: Install AWX on Alma Linux 9
  gather_facts: true
  hosts: all
  become: yes
  tasks:
    - name: Install kubnetes
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -

    - name: Kustomize Script
      ansible.builtin.shell: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - name: Move Kustomize file
      ansible.builtin.shell: mv /home/zgadmin/kustomize /usr/local/bin
    
    - name: Download Kustomize.yaml file
      ansible.builtin.shell:  